openapi: 3.0.0
info:
  title: Заказ на ресурсы облака
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1/
    description: Dev server
paths:
  /clouds:
    get:
      summary: Метод получения списка ресурсов на облако 
      tags:
        - Clouds
      operationId: getAllClouds
      responses:
        "200":
            description: Успешный ответ со списком ресурсов в облаке
            content:
              adplication/json:
                schema:
                  $ref: "#/components/schemas/Cloud"
        "default":
            description: Все остальное
            content:
              adplication/json:
                schema:
                  $ref: "#/components/schemas/Error"
  /clouds/{CPU}/{HDD}/{RAM}/{OS}:

    post:
      summary: Метод создания заказа на облако
      tags:
        - Clouds
      operationId: createCloud
      parameters:
        - name: CPU
          in: path
          required: true
          description: Количество ядер CPU
          schema:
            type: string
          example: 24 ядра
        - name: HDD
          in: path
          required: true
          description: объем HDD
          schema:
            type: string
          example: 150Tb
        - name: RAM
          in: path
          required: true
          description: объем RAM
          schema:
            type: string
          example: 128Gb
        - name: OS
          in: path
          required: true
          description: операционная система
          schema:
            type: string
          example: Windows
      requestBody:
        required: true
        content:
          adplication/json:
            schema:
              $ref: "#/components/schemas/Error"
      responses:
        "200":
          description: Успешный ответ создания заказа в облаке
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Cloud"
        "default":
          description: Все остальное
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error"
  /clouds/{cloud_id}:
    get:
      summary: Метод получения заказа ресурсов на облако по ID
      tags:
        - Clouds
      operationId: getCloudById
      parameters:
        - name: cloud_id
          in: path
          required: true
          description: Идентификатор заказа облака
          schema:
            type: string
          example: f102b615
      responses:
        "200":
           description: Успешный ответ заказом облака по ID
           content:
              adplication/json:
                schema:
                  $ref: "#/components/schemas/Cloud"
        "default":
            description: Все остальное
            content:
              adplication/json:
                schema:
                  $ref: "#/components/schemas/Error"
    delete:
      summary: Метод отмены заказа на облако по ID
      tags: 
        - Clouds
      operationId: cencelCloudById
      parameters:
        - name: cloud_id
          in: path
          required: true
          description: Идентификатор заказа облака
          schema:
            type: string
          example: f102b615
      responses:
        "200":
          description: Успешный ответ заказом облака по ID
          content:
            adplication/json: {}
        "default":
          description: Все остальное
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Cloud:
      type: object
      required:
        - id_customer
        - OS
        - RAM
        - CPU
        - PS_id
        - HDD
      properties:
        cloud_id:
          type: string
          example: f102b615
        id_customer:
          type: string
          example: f102b615
        OS:
          type: string
          enum:
            - Windows
            - Linux
          description: Операционная система сервера
        RAM:
          type: string
          example: 128
        CPU:
          type: string
          example: 24 ядра
        PS_id:
          type: string
          example: 192.165.1.1, 192.165.1.125
        HDD:
          type: string
          example: 150Tb
    Clouds:
      type: array
      items:
        $ref: "#/components/schemas/Cloud"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string